name: matrix2d
description: Matrix 2D is a package for mathematical 2D array functions and manipulations in Dart, similar to NumPy
version: 1.0.4
homepage: 'https://github.com/n4ze3m/matrix2d'

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dev_dependencies:
  test: ^1.7.3